export const FETCH_PLANTS_REQUEST = 'FETCH_PLANTS_REQUEST'
export const FETCH_PLANTS_SUCCESS = 'FETCH_PLANTS_SUCCESS'
export const FETCH_PLANTS_FAILURE = 'FETCH_PLANTS_FAILURE'
export const WATER_PLANT_POST = 'WATER_PLANT_POST'